PREFIX rdfs:		<http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc:			<http://purl.org/dc/elements/1.1/>
PREFIX xsd:			<http://www.w3.org/2001/XMLSchema#>

PREFIX foundation:	<http://siedepartment.com/SIE_Foundation/SIE_Foundation#>

PREFIX agent:	<http://siedepartment.com/SIE_Core/SIE_Agent#>
PREFIX event:	<http://siedepartment.com/SIE_Core/SIE_Event#>
PREFIX info:	<http://siedepartment.com/SIE_Core/SIE_Information#>
PREFIX meas:	<http://siedepartment.com/SIE_Core/SIE_Measurement#>
PREFIX prov:	<http://siedepartment.com/SIE_Core/SIE_Provenance#>

PREFIX acq:		<http://siedepartment.com/SIE_Domain/SIE_Acquisition#>
PREFIX data:	<http://siedepartment.com/SIE_Domain/SIE_DataManagement#>
PREFIX mission:	<http://siedepartment.com/SIE_Domain/SIE_Mission#>
PREFIX ms:		<http://siedepartment.com/SIE_Domain/SIE_ModelingAndSimulation#>
PREFIX pm:		<http://siedepartment.com/SIE_Domain/SIE_ProjectManagement#>
PREFIX req:		<http://siedepartment.com/SIE_Domain/SIE_Requirements#>
PREFIX sw:		<http://siedepartment.com/SIE_Domain/SIE_Software#>
PREFIX sa:		<http://siedepartment.com/SIE_Domain/SIE_SystemArchitecture#>
PREFIX test:	<http://siedepartment.com/SIE_Domain/SIE_Test#>

PREFIX temp_dec:	<http://siedepartment.com/DoD_TEMP_Framework/TEMP_Decision#>
PREFIX temp_ear:	<http://siedepartment.com/DoD_TEMP_Framework/TEMP_ExecutionAndReporting#>
PREFIX temp_org:	<http://siedepartment.com/DoD_TEMP_Framework/TEMP_Organization#>
PREFIX temp_resp:	<http://siedepartment.com/DoD_TEMP_Framework/TEMP_Responsibility#>
PREFIX temp_teo:	<http://siedepartment.com/DoD_TEMP_Framework/TEMP_TEOversight#>
PREFIX temp_tpf:	<http://siedepartment.com/DoD_TEMP_Framework/TEMP_TestProgramFrameworks#>
PREFIX temp_tpp:	<http://siedepartment.com/DoD_TEMP_Framework/TEMP_TestProgramPolicy#>
PREFIX temp_tps:	<http://siedepartment.com/DoD_TEMP_Framework/TEMP_TestProgramStructure#>
PREFIX temp_tpt:	<http://siedepartment.com/DoD_TEMP_Framework/TEMP_TestProgramTeams#>



SELECT DISTINCT ?TimePeriodStart ?TimePeriodEnd ?Event

WHERE {
    ?TimePeriod a foundation:TemporalRegion .
    ?TimePeriod foundation:hasBeginInstant ?TimePeriodStart .
    ?TimePeriod foundation:hasEndInstant ?TimePeriodEnd .
    ?Event event:occursOn ?TimePeriod .
}
ORDER BY ASC (?TimePeriodStart)